### ISSUE TITLE
Panal for time development of center speed.

### ISSUE THREAD

**Issue by nobuaki-mzmt** [nobuaki-mzmt/tandem_visualizer#3]
左の "[ind] _ center _ [x,y]" の時間発展の図ですが、 center よりも head や tail の方がいいと思われます。（例えばhead と tailが反転するようなイベントが他の種のトラッキングで起きるんですが、それにcenterだと気づけない）
label 選択を可能にするならば、そこでどれを表示するか選べるようにできると便利かと思いました。

**Comment by tkdsym2** [comment]
#5 で追加
